// <auto-generated />
namespace Learning.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Session : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Session));
        
        string IMigrationMetadata.Id
        {
            get { return "201802200735154_Session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
